backend:
  name: github
  repo: arthur-fontaine/arthurfontaine.fr
  branch: use-netlify-cms
media_folder: "public/media"
public_folder: "/media"
collections:
  - label: "My website"
    name: "my-website"
    files:
      - label: "About Page"
        name: "about"
        description: "About page content"
        file: "data/about.json"
        fields:
          - { label: "Content", name: "content", widget: "markdown" }
      - label: "Social"
        name: "social"
        description: "Social links"
        file: "data/social.json"
        fields:
          - { label: "Social", name: "social", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Link", name: "link", widget: "string" },
              { label: "Icon", name: "icon", widget: "file" }
            ] }
      - label: "Contact"
        name: "contact"
        description: "Contact information"
        file: "data/contact.json"
        fields:
          - { label: "Email", name: "email", widget: "string" }
      - label: "Resume"
        name: "resume"
        description: "Resume"
        file: "data/resume.json"
        fields:
          - { label: "Resume", name: "resume", widget: "file" }
      - label: "Projects"
        name: "projects"
        description: "Projects"
        file: "data/projects.json"
        fields:
          - { label: "Projects", name: "projects", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Baseline" , name: "baseline", widget: "string" },
              { label: "Description", name: "description", widget: "string" },
              { label: "Github", name: "github", widget: "string", required: false },
              { label: "Website", name: "website", widget: "string", required: false },
              { label: 'Color', name: 'color', widget: 'color' },
              { label: "Tags", name: "tags", widget: "list" }
            ] }
  - label: "Redirects"
    name: "redirects"
    files:
      - label: "Redirects"
        name: "redirects"
        description: "Redirects"
        file: "data/redirects.json"
        fields:
          - { label: "Redirects", name: "redirects", widget: "list", fields: [
              { label: "From", name: "from", widget: "string" },
              { label: "To", name: "to", widget: "string" },
            ] }
